### ISSUE TITLE
Fix styling of action buttons in surveylist

### ISSUE THREAD

**Issue by tuur29** [decrn/localsurvey#42]
https://github.com/decrn/localsurvey/blob/master/src/containers/homepage/survey-list.component.tsx#L50

Brought up here: https://github.com/decrn/localsurvey/pull/38#issuecomment-461620375

Perhaps look for some kind of drop down buttons?

**Comment by decrn** [comment]
I really like it already. Maybe we should use the dropdown on all screen widths. Then we can make all the columns a fixed width, and just widen the "name" column to fit the viewport.

(This is a minor nuisance right now. Try filtering from "Published" to "Draft" in different screen widths and you will notice the resizing effect)
